security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Telegraf\ChecklistBundle\Document\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        my_mongo_provider:
            mongodb: {class: Telegraf\ChecklistBundle\Document\User, property: username}
            
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
                default_target_path: homepage
            logout:
                path:   /logout
                target: homepage

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
