homepage:
    pattern:  /
    defaults: { _controller: TelegrafChecklistBundle:Default:index }
create_item:
    pattern:  /createItem
    defaults: { _controller: TelegrafChecklistBundle:Default:createItem }
edit_item:
    pattern:  /editItem/{id}
    defaults: { _controller: TelegrafChecklistBundle:Default:editItem }
    options:
        expose: true
update_item:
    pattern:  /updateItem
    defaults: { _controller: TelegrafChecklistBundle:Default:updateItem }
delete_item:
    pattern:  /deleteItem
    defaults: { _controller: TelegrafChecklistBundle:Default:deleteItem }
tick_item:
    pattern:  /tickItem
    defaults: { _controller: TelegrafChecklistBundle:Default:tickItem }
    options:
        expose: true
