homepage:
    pattern:  /hello
    defaults: { _controller: TelegrafChecklistBundle:Default:index }
create_item:
    pattern:  /createItem
    defaults: { _controller: TelegrafChecklistBundle:Default:createItem }
update_item:
    pattern:  /updateItem/{id}/{text}
    defaults: { _controller: TelegrafChecklistBundle:Default:updateItem }
delete_item:
    pattern:  /deleteItem
    defaults: { _controller: TelegrafChecklistBundle:Default:deleteItem }
tick_item:
    pattern:  /tickItem
    defaults: { _controller: TelegrafChecklistBundle:Default:tickItem }