homepage:
    pattern:  /
    defaults: { _controller: TelegrafChecklistBundle:Default:index }
create_item:
    pattern:  /createItem
    defaults: { _controller: TelegrafChecklistBundle:Default:createItem }
show_item:
    pattern:  /showItem/{id}
    defaults: { _controller: TelegrafChecklistBundle:Default:showItem }
    options:
        expose: true
edit_item:
    pattern:  /editItem/{id}
    defaults: { _controller: TelegrafChecklistBundle:Default:editItem }
    options:
        expose: true
update_item:
    pattern:  /updateItem
    defaults: { _controller: TelegrafChecklistBundle:Default:updateItem }
delete_item:
    pattern:  /deleteItem
    defaults: { _controller: TelegrafChecklistBundle:Default:deleteItem }
undo_delete_item:
    pattern:  /undoDeleteItem
    defaults: { _controller: TelegrafChecklistBundle:Default:undoDeleteItem }
tick_item:
    pattern:  /tickItem
    defaults: { _controller: TelegrafChecklistBundle:Default:tickItem }
    options:
        expose: true
import_items:
    pattern:  /importing
    defaults: { _controller: TelegrafChecklistBundle:Default:importItems }
