parameters:
#    telegraf_checklist.example.class: Telegraf\ChecklistBundle\Example

services:
#    telegraf_checklist.example:
#        class: %telegraf_checklist.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
