parameters:
#    telegraf_checklist.example.class: Telegraf\ChecklistBundle\Example

services:
#    telegraf_checklist.example:
#        class: %telegraf_checklist.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    telegraf_checklist.registration:
        class: Telegraf\ChecklistBundle\EventListener\RegistrationListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }

    telegraf_checklist.login:
        class: Telegraf\ChecklistBundle\EventListener\LoginListener
        arguments: [@router]
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login', method: 'onSecurityInteractiveLogin' }